Process SpawnPoolWorker-6: Traceback (most recent call last): File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap self.run() File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/process.py", line 108, in run self._target(self._args, **self._kwargs) File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/pool.py", line 114, in worker task = get() File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/queues.py", line 358, in get return _ForkingPickler.loads(res) AttributeError: Can't get attribute 'varimp_experiment' on Process SpawnPoolWorker-1: Traceback (most recent call last): File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap self.run() File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/process.py", line 108, in run self._target(self._args, self._kwargs) File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/pool.py", line 114, in worker task = get() File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/queues.py", line 358, in get return _ForkingPickler.loads(res) AttributeError: Can't get attribute 'varimp_experiment' on Process SpawnPoolWorker-4: Traceback (most recent call last): File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap self.run() File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/process.py", line 108, in run self._target(*self._args, self._kwargs) File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/pool.py", line 114, in worker task = get() File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/queues.py", line 358, in get return _ForkingPickler.loads(res) AttributeError: Can't get attribute 'varimp_experiment' on Process SpawnPoolWorker-3: Traceback (most recent call last): File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap self.run() File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/process.py", line 108, in run self._target(self._args, **self._kwargs) File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/pool.py", line 114, in worker task = get() File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/queues.py", line 358, in get return _ForkingPickler.loads(res) AttributeError: Can't get attribute 'varimp_experiment' on Process SpawnPoolWorker-7: Traceback (most recent call last): File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap self.run() File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/process.py", line 108, in run self._target(self._args, self._kwargs) File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/pool.py", line 114, in worker task = get() File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/queues.py", line 358, in get return _ForkingPickler.loads(res) AttributeError: Can't get attribute 'varimp_experiment' on Process SpawnPoolWorker-2: Traceback (most recent call last): File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap self.run() File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/process.py", line 108, in run self._target(*self._args, self._kwargs) File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/pool.py", line 114, in worker task = get() File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/queues.py", line 358, in get return _ForkingPickler.loads(res) AttributeError: Can't get attribute 'varimp_experiment' on Process SpawnPoolWorker-5: Traceback (most recent call last): File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap self.run() File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/pool.py", line 114, in worker task = get() File "/Users/Ray/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/queues.py", line 358, in get return _ForkingPickler.loads(res) AttributeError: Can't get attribute 'varimp_experiment' on
